#!/bin/bash
# RaspberryPi MediaCentre Installer
# Author: Alan Pich
# Website: https://github.com/alanpich
# Date: 13 June 2012
# Version 1.0


# VARIABLE DEFINITIONS
ZIPURL="https://github.com/alanpich/rPI-media-centre/zipball/master"
RPIMC_PATH="/etc/rPImc"
USER=exec whoami
GROUP="rpi-mc"



# CHECK FOR A PACKAGE, INSTALL IT IF NOT FOUND
function require {
	echo -n " Checking $1... "
	if which $1 >/dev/null; then
		success
	else
		fail
		# Install quietly without confirmation prompts
		# sudo apt-get -qy install $1 >/dev/tty1
	fi
}

# COLOURED OUTPUT 
function purple {
	echo -e "\e[01;35m$*\e[00m"
}

function fail {
	echo -e "\e[00;31mNO\e[00m"
}

function success {
	echo -e "\e[00;32mOK\e[00m"
}




# Install Script --------------------------------------------------------------
clear;
purple "---------------------------------------------------"
purple "::             RaspberryPi MediaCenter           ::"
purple "---------------------------------------------------"
echo " This script will install all required packages to "
echo " run a media centre on your rPI and control it via "
echo " a web interface."
echo

# REDUNDANT SUDO COMMAND TO CACHE PASSWORD
echo " Installation requires root (sudo) privileges."
echo " Please enter your password"
sudo ls >/dev/null


# CHECK FOR ALL REQUIRED PACKAGES AND INSTALL ANY MISSING
echo
purple " :: CHECKING DEPENDENCIES"
purple " ----------------------------------"
require apache2
require php5
require php5-cli
require mysql-
require fusesmb
require unzip
echo

# GET NESCESARY FILES AND EXTRACT TO THE CORRECT PLACES 
purple " :: INSTALLING INTERFACE"
purple " ----------------------------------"

# CREATE USER GROUP IF IT DOESNT EXISTS
echo -n " Adding group $GROUP...          "
TMP=`egrep -i "^$GROUP" /etc/group`
if [ $TMP = "" ]; then
	sudo groupadd $GROUP
fi
success

# CREATE INSTALL DIRECTORY IF IT DOESNT EXIST
echo -n " Checking install path...        "
if [ ! -e $RPIMC_PATH ]; then
	sudo mkdir $RPIMC_PATH
fi
success

# CHOWN INSTALL DIR TO SPECIFIED USER AND GROUP
echo -n " Checking permissions...         "
sudo chown  $USER:$GROUP $RPIMC_PATH
success

# DOWNLOAD LATEST BUILD FROM GITHUB
echo -n " Downloding git repo...          "
wget -q $ZIPURL 
mv master rPI-media-centre.zip
success

# EXTRACT FILES TO INSTALL PATH
echo -n " Extracting archive...           "
unzip -qq -o rPI-media-centre.zip -d $RPIMC_PATH

# ORGANISE FILES PROPERLY
DIR=`ls $RPIMC_PATH | sort -n | head -1`
mv $RPIMC_PATH/$DIR/* $RPIMC_PATH
rm -rf $RPIMC_PATH/$DIR
success
echo

# SET UP APACHE TO SERVE THE CORRECT DIRECTORIES
purple " :: SETTING UP APACHE (to do)"
purple " ----------------------------------"
echo -n " Setting up envvars...           " && success
echo -n " Setting up sites-available...   " && success
echo -n " Enabling mod_rewrite...         " && success
echo

# SET UP USER .profile WITH ALIASES & NETWORK MOUNT
purple " :: SETTING UP USER ENVIRONMENT (to do)"
purple " ----------------------------------"
echo -n " Adding startup scripts...       " && success
echo -n " Mounting network shares...      " && success
echo -n " Restarting apache service...    " 
sudo service apache2 restart >/dev/null && success


echo
