#!/bin/bash
# RaspberryPi MediaCentre Installer
# Author: Alan Pich
# Website: https://github.com/alanpich
# Date: 13 June 2012
# Version 1.0


################################################################################
###   V A R I A B L E   D E F I N I T I O N S                                  #
################################################################################

# URL TO rPImc source (github for latest version)
GITURL="https://github.com/alanpich/rPImc.git"

# Install path for rPImc files
RPIMC_PATH="/etc/rPImc"

# User to run rPImc under
USER=`whoami`

# Primary group for rPImc
GROUP=`id -gn`




################################################################################
###   U S E F U L   F U N C T I O N S                                          #
################################################################################

# PAD A STRING TO 
function pad {
	echo -n "  "$1"..." | sed -e :a -e 's/^.\{1,32\}$/& /;ta'
} 


# CHECK FOR A PACKAGE, INSTALL IT IF NOT FOUND
function require {
	pad "Installing $1"
	if which $1 >/dev/null; then
		success
	else
		# Install quietly without confirmation prompts
		sudo apt-get -qy install $1 >/dev/null && success
	fi
}

# COLOURED OUTPUT 
function purp {	echo -e "\e[01;35m$*\e[00m" ;}
function fail {	echo -e "\e[01;31mNO\e[00m";}
function success {	echo -e "\e[00;32mOK\e[00m";}


export RPIMC_PATH="$RPIMC_PATH"

################################################################################
###   M A I N   I N S T A L L E R   S C R I P T                                #
################################################################################

clear;
purp "---------------------------------------------------"
purp "::             RaspberryPi MediaCenter           ::"
purp "---------------------------------------------------"
echo " This script will install all required packages to "
echo " run a media centre on your rPI and control it via "
echo " a web interface."
echo

# REDUNDANT SUDO COMMAND TO CACHE PASSWORD
echo " Installation requires root (sudo) privileges."
echo " Please enter your password if prompted"
sudo ls >/dev/null


# CHECK FOR ALL REQUIRED PACKAGES AND INSTALL ANY MISSING
echo
purp " :: INSTALLING DEPENDENCIES"
purp " ----------------------------------"
require git-core
require apache2
require php5
require fusesmb
echo

# GET NESCESARY FILES AND EXTRACT TO THE CORRECT PLACES 
purp " :: INSTALLING INTERFACE"
purp " ----------------------------------"

# CREATE USER GROUP IF IT DOESNT EXISTS
pad "Adding group $GROUP"
if [ `egrep -i "^$GROUP" /etc/group` = "" ]; then
	sudo groupadd $GROUP
fi
success

# CREATE INSTALL DIRECTORY IF IT DOESNT EXIST
if [ ! -e $RPIMC_PATH ]; then
	pad "Installing source"
	sudo mkdir $RPIMC_PATH >/dev/null &&
	sudo chown $USER:$GROUP $RPIMC_PATH >/dev/null &&
	git clone -q $GITURL $RPIMC_PATH >/dev/null && success
else
	if [ ! -e $RPIMC_PATH/.git ]; then
		pad "Installing source"
		git clone -q $GITURL $RPIMC_PATH >/dev/null && success
	else 
		pad "Updating source"
		git init -q  $RPIMC_PATH >/dev/null &&
		git fetch -q >/dev/null && success
	fi

fi



# SET UP APACHE TO SERVE THE CORRECT DIRECTORIES
purp " :: SETTING UP APACHE (to do)"
purp " ----------------------------------"

# Generate a sites-available/default file for apache
pad "Setting up sites-available"
sudo cp -f $RPIMC_PATH/.install/apache-sites-available-default /etc/apache2/sites-available/default && success

# Generate the envvars file for apache
pad "Setting up envvars"
sudo cp -f $RPIMC_PATH/.install/apache-envvars /etc/apache2/envvars && success

# Enable mod_rewrite for apache
pad "Enabling mod_rewrite" 
sudo a2enmod -q rewrite >/dev/null && success

# Give a ServerName to stop apache whining
echo "ServerName rPImc" | sudo tee -a /etc/apache2/httpd.conf >/dev/null




# SET UP USER .profile WITH ALIASES & NETWORK MOUNT
purp " :: SETTING UP USER ENVIRONMENT (to do)"
purp " ----------------------------------"
pad "Adding startup scripts" 
echo 'export RPIMC_PATH="'$RPIMC_PATH'"' | sudo tee -a /home/$USER/.profile >/dev/null
echo "$RPIMC_PATH/rPImc.profile" | sudo tee -a /home/$USER/.profile >/dev/null
success

# Mount network shares
pad "Mounting network shares"
sudo fusesmb $RPIMC_PATH/network -o allow_other -o nonempty && success

# Enable sound over HDMI
pad "Enabling HDMI sound"
sudo modprobe snd_bcm2835 & success

pad "Restarting apache service" 
sudo service apache2 restart >/dev/null && success


echo
